-- MySQL Script generated by MySQL Workbench
-- Wed Feb 26 20:59:35 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema strock_control
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema strock_control
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `strock_control` DEFAULT CHARACTER SET utf8 ;
USE `strock_control` ;

-- -----------------------------------------------------
-- Table `strock_control`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strock_control`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `quantity` INT NOT NULL,
  `min_stock` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_DATETIME,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `strock_control`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strock_control`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `type` ENUM('administrator', 'default') NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_DATETIME,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `strock_control`.`log_moviments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strock_control`.`log_moviments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `type` ENUM('input', 'output') NOT NULL,
  `quantity` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_DATETIME,
  INDEX `fk_log_manager_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_log_manager_product1_idx` (`product_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_log_manager_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `strock_control`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_log_manager_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `strock_control`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `strock_control`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strock_control`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_DATETIME,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_category_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_category_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `strock_control`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `strock_control`.`log_access`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strock_control`.`log_access` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_DATETIME,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_log_access_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_log_access_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `strock_control`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
