-- MySQL Script generated by MySQL Workbench
-- Wed Feb 26 21:28:54 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS,
                         UNIQUE_CHECKS=0;


SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS,
                              FOREIGN_KEY_CHECKS=0;


SET @OLD_SQL_MODE=@@SQL_MODE,
                    SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema stock_control
-- -----------------------------------------------------
 -- -----------------------------------------------------
-- Schema stock_control
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `stock_control` DEFAULT CHARACTER
SET utf8 ;

USE `stock_control` ;

-- -----------------------------------------------------
-- Table `stock_control`.`product`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `stock_control`.`product` (`id` INT NOT NULL AUTO_INCREMENT,
                                                                        `name` VARCHAR(255) NOT NULL,
                                                                                            `description` TEXT NULL,
                                                                                                               `quantity` INT NOT NULL,
                                                                                                                              `min_stock` INT NOT NULL,
                                                                                                                                              `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                                                                                                                                                     PRIMARY KEY (`id`));

-- -----------------------------------------------------
-- Table `stock_control`.`account`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `stock_control`.`account` (`id` INT NOT NULL AUTO_INCREMENT,
                                                                        `full_name` VARCHAR(255) NOT NULL,
                                                                                                 `email` VARCHAR(255) NOT NULL,
                                                                                                                      `password` VARCHAR(255) NOT NULL,
                                                                                                                                              `type` ENUM('administrator', 'default') NOT NULL,
                                                                                                                                                                                      `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                                                                                                                                                                                             PRIMARY KEY (`id`), UNIQUE INDEX `email_UNIQUE` (`email` ASC));

-- -----------------------------------------------------
-- Table `stock_control`.`log_moviments`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `stock_control`.`log_moviments`
  (`id` INT NOT NULL AUTO_INCREMENT,
                     `accont_id` INT NOT NULL,
                                     `product_id` INT NOT NULL,
                                                      `type` ENUM('input', 'output') NOT NULL,
                                                                                     `quantity` INT NOT NULL,
                                                                                                    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                                                                                                           INDEX `fk_log_manager_user_idx` (`accont_id` ASC),
                                                                                                                                                 INDEX `fk_log_manager_product1_idx` (`product_id` ASC),
                                                                                                                                                       PRIMARY KEY (`id`), CONSTRAINT `fk_log_manager_user`
   FOREIGN KEY (`accont_id`) REFERENCES `stock_control`.`account` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
                                                                                                          CONSTRAINT `fk_log_manager_product1`
   FOREIGN KEY (`product_id`) REFERENCES `stock_control`.`product` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION);

-- -----------------------------------------------------
-- Table `stock_control`.`category`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `stock_control`.`category` (`id` INT NOT NULL AUTO_INCREMENT,
                                                                         `name` VARCHAR(32) NOT NULL,
                                                                                            `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                                                                                                   PRIMARY KEY (`id`));

-- -----------------------------------------------------
-- Table `stock_control`.`log_access`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `stock_control`.`log_access`
  (`id` INT NOT NULL AUTO_INCREMENT,
                     `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                            `account_id` INT NOT NULL,
                                                                             PRIMARY KEY (`id`), INDEX `fk_log_access_user1_idx` (`account_id` ASC),
                                                                                                       CONSTRAINT `fk_log_access_user1`
   FOREIGN KEY (`account_id`) REFERENCES `stock_control`.`account` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION);

-- -----------------------------------------------------
-- Table `stock_control`.`category_has_product`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `stock_control`.`category_has_product`
  (`category_id` INT NOT NULL,
                     `product_id` INT NOT NULL,
                                      PRIMARY KEY (`category_id`,
                                                   `product_id`), INDEX `fk_category_has_product_product1_idx` (`product_id` ASC),
                                                                        INDEX `fk_category_has_product_category1_idx` (`category_id` ASC),
                                                                              CONSTRAINT `fk_category_has_product_category1`
   FOREIGN KEY (`category_id`) REFERENCES `stock_control`.`category` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
                                                                                                             CONSTRAINT `fk_category_has_product_product1`
   FOREIGN KEY (`product_id`) REFERENCES `stock_control`.`product` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;


SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;


SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

